# Generated by Django 5.0.2 on 2024-03-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('is_collected', models.BooleanField(default=False)),
            ],
        ),
    ]
