# Generated by Django 5.0.2 on 2024-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_ID', models.CharField(max_length=50, unique=True)),
                ('company_description', models.TextField()),
                ('company_password', models.CharField(max_length=128)),
            ],
        ),
    ]
